# -*- coding: utf-8 -*-
"""Konvolusi manual fix

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11n4qXD7xU8mdCNcRmKUX9_IBI70398yc
"""

from PIL import Image
import urllib.request
import numpy as np
import cv2
from google.colab.patches import cv2_imshow

img = cv2.imread('/content/kaleng92.jpg')
cv2_imshow(img)
#old_img = Image.open(data)

img.shape

img

#Inputan asli size 614
resize_asli = cv2.resize(img,(614, 614))
cv2_imshow(resize_asli)

# Commented out IPython magic to ensure Python compatibility.
#Convolution Layer

import matplotlib.pyplot as plt
# %matplotlib inline

from skimage import data
from skimage.io import imread
from skimage.color import rgb2gray
import numpy as np

import cv2

kernel = np.array([[0, -1, 0],
                   [-1, 4,-1],
                   [0, -1, 0]])
output = cv2.filter2D(resize_asli,-1, kernel)
fig, axes = plt.subplots(1,2, figsize=(12,12))
ax = axes.ravel()

ax[0].imshow(output)

#Resize Manipulasi

resize_img = cv2.resize(img,(8,8))

resize_img