# -*- coding: utf-8 -*-
"""Training YOLO V7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-hzVo4U71MI7QL_iT9A1T480Fo3qlNSp
"""

#Import Library
import torch, torchvision

# Commented out IPython magic to ensure Python compatibility.
#Install YOLOv7
!git clone https://github.com/WongKinYiu/yolov7.git
# %cd yolov7
# %pip install -qr requirements.txt
!wget https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7_training.pt

!unzip /content/train_data.zip

# Training
!python train.py --img 640 --batch 17 --epochs 300  --data custom_data.yaml --weights yolov7_training.pt --cfg cfg/training/yolov7.yaml --hyp data/hyp.scratch.custom.yaml